In [1]:
# ----------
# User Instructions:
# 
# Create a function compute_value which returns
# a grid of values. The value of a cell is the minimum
# number of moves required to get from the cell to the goal. 
#
# If a cell is a wall or it is impossible to reach the goal from a cell,
# assign that cell a value of 99.
# ----------
import numpy as np
from collections import deque

grid = np.array([[0, 1, 0, 0, 0, 0],
                [0, 1, 0, 0, 0, 0],
                [0, 1, 0, 0, 0, 0],
                [0, 1, 0, 0, 0, 0],
                [0, 0, 0, 0, 1, 0]])
goal = [len(grid)-1, len(grid[0])-1]
cost = 1 # the cost associated with moving from a cell to an adjacent one

delta = [[-1, 0 ], # go up
         [ 0, -1], # go left
         [ 1, 0 ], # go down
         [ 0, 1 ]] # go right

delta_name = ['^', '<', 'v', '>']

N, M = grid.shape
value = np.zeros_like(grid)
visit = np.zeros_like(grid)-9

def get_children(r, c, v, visit):
    children = []
    for dr, dc in delta:
        nr = r + dr
        nc = c + dc
        if (0 <= nr < N) and (0 <= nc < M) and grid[nr][nc] == 0 and visit[nr][nc]== -9:
            children.append([nr, nc, v+1])
    return children

que = deque([[goal[0], goal[1], 0]])
it = 0
while len(que) > 0:
    r, c, v = que.popleft()
    visit[r][c] = it + 1
    value[r][c] = v
    print("{:03d}:\t ({}, {}) : {}".format(it, r, c, v))
    for child in get_children(r, c, v, visit):
#         if child not in que:
        que.append(child)
    it +=1

000:	 (4, 5) : 0
001:	 (3, 5) : 1
002:	 (2, 5) : 2
003:	 (3, 4) : 2
004:	 (1, 5) : 3
005:	 (2, 4) : 3
006:	 (2, 4) : 3
007:	 (3, 3) : 3
008:	 (0, 5) : 4
009:	 (1, 4) : 4
010:	 (1, 4) : 4
011:	 (2, 3) : 4
012:	 (1, 4) : 4
013:	 (2, 3) : 4
014:	 (2, 3) : 4
015:	 (3, 2) : 4
016:	 (4, 3) : 4
017:	 (0, 4) : 5
018:	 (0, 4) : 5
019:	 (1, 3) : 5
020:	 (0, 4) : 5
021:	 (1, 3) : 5
022:	 (1, 3) : 5
023:	 (2, 2) : 5
024:	 (0, 4) : 5
025:	 (1, 3) : 5
026:	 (1, 3) : 5
027:	 (2, 2) : 5
028:	 (1, 3) : 5
029:	 (2, 2) : 5
030:	 (2, 2) : 5
031:	 (4, 2) : 5
032:	 (4, 2) : 5
033:	 (0, 3) : 6
034:	 (0, 3) : 6
035:	 (0, 3) : 6
036:	 (1, 2) : 6
037:	 (0, 3) : 6
038:	 (0, 3) : 6
039:	 (1, 2) : 6
040:	 (0, 3) : 6
041:	 (1, 2) : 6
042:	 (1, 2) : 6
043:	 (0, 3) : 6
044:	 (0, 3) : 6
045:	 (1, 2) : 6
046:	 (0, 3) : 6
047:	 (1, 2) : 6
048:	 (1, 2) : 6
049:	 (0, 3) : 6
050:	 (1, 2) : 6
051:	 (1, 2) : 6
052:	 (1, 2) : 6
053:	 (4, 1) : 6
054:	 (4, 1) : 6
055:	 (0, 2) : 7
056:	 (0, 2) : 7
057:	 (0, 2) : 7
058:	 (0, 2) :

In [2]:
print(visit)

[[85 -9 75 50 25  9]
 [83 -9 53 29 13  5]
 [81 -9 31 15  7  3]
 [79 -9 16  8  4  2]
 [77 55 33 17 -9  1]]


In [3]:
print(value)

[[11  0  7  6  5  4]
 [10  0  6  5  4  3]
 [ 9  0  5  4  3  2]
 [ 8  0  4  3  2  1]
 [ 7  6  5  4  0  0]]


In [4]:
from collections import deque

def compute_value(grid,goal,cost):
    # ----------------------------------------
    # insert code below
    # ----------------------------------------
    
    N = len(grid)
    M = len(grid[0])
    value = [[9 for col in range(len(grid[0]))] for row in range(len(grid))]
    visit = [[0 for col in range(len(grid[0]))] for row in range(len(grid))]
    
    que = deque([[goal[0], goal[1], 0]])
    
    while len(que) > 0:
        r, c, v = que.popleft()
        visit[r][c] = 1
        value[r][c] = v
        
        for dr, dc in delta:
            nr = r + dr
            nc = c + dc
            if (0 <= nr < N) and (0 <= nc < M) and visit[nr][nc] == 0 and grid[nr][nc] == 0:
                que.append([nr, nc, v+cost])

    return value

In [5]:
val = compute_value(grid,goal,cost)

In [6]:
from pprint import pprint
pprint(val)

[[11, 9, 7, 6, 5, 4],
 [10, 9, 6, 5, 4, 3],
 [9, 9, 5, 4, 3, 2],
 [8, 9, 4, 3, 2, 1],
 [7, 6, 5, 4, 9, 0]]


In [7]:
delta_name = ['^', '<', 'v', '>']

In [8]:
grid = [[0, 0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1, 0],
        [0, 0, 1, 1, 1, 0],
        [0, 0, 0, 0, 1, 0]]
goal = [5,5]

In [9]:
def optimum_policy(grid,goal,cost):
    N = len(grid)
    M = len(grid[0])
    value = [[99 for col in range(len(grid[0]))] for row in range(len(grid))]
    visit = [[0 for col in range(len(grid[0]))] for row in range(len(grid))]
    policy = [['≈' for col in range(len(grid[0]))] for row in range(len(grid))]
    
    que = deque([[goal[0], goal[1], 0]])
    
    while len(que) > 0:
        r, c, v = que.popleft()
        visit[r][c] = 1
        value[r][c] = v
        for (dr, dc), d_name in zip(delta, delta_name):
            nr = r + dr
            nc = c + dc
            if (0 <= nr < N) and (0 <= nc < M) and visit[nr][nc] == 0 and grid[nr][nc] == 0:
                que.append([nr, nc, v+1])
       
    visit = [[0 for col in range(len(grid[0]))] for row in range(len(grid))]
    for r in range(N):
        for c in range(M):
            if grid[r][c] == 1:
                continue
            ways = []
            for (dr, dc), d_name in zip(delta, delta_name):
                nr = r + dr
                nc = c + dc
                
                if (0 <= nr < N) and (0 <= nc < M) and visit[nr][nc] == 0 and grid[nr][nc] == 0:
                    ways.append([value[nr][nc], d_name])
            
            if(len(ways) > 0):
                ways.sort()
                policy[r][c] = ways[0][1]
    policy[goal[0]][goal[1]] = '*'
    pprint(value)
    return policy

In [10]:
pprint(grid)
pol = optimum_policy(grid,goal,cost)
pprint(pol)

[[0, 0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 1, 0],
 [0, 0, 1, 1, 1, 0],
 [0, 0, 0, 0, 1, 0]]
[[12, 11, 99, 7, 6, 5],
 [11, 10, 99, 6, 5, 4],
 [10, 9, 99, 5, 4, 3],
 [9, 8, 7, 6, 99, 2],
 [10, 9, 99, 99, 99, 1],
 [11, 10, 11, 12, 99, 0]]
[['>', 'v', '≈', '>', '>', 'v'],
 ['>', 'v', '≈', '>', '>', 'v'],
 ['>', 'v', '≈', '>', '>', 'v'],
 ['>', '>', '>', '^', '≈', 'v'],
 ['>', '^', '≈', '≈', '≈', 'v'],
 ['>', '^', '<', '<', '≈', '*']]


In [11]:
# ----------
# User Instructions:
# 
# Implement the function optimum_policy2D below.
#
# You are given a car in grid with initial state
# init. Your task is to compute and return the car's 
# optimal path to the position specified in goal; 
# the costs for each motion are as defined in cost.
#
# There are four motion directions: up, left, down, and right.
# Increasing the index in this array corresponds to making a
# a left turn, and decreasing the index corresponds to making a 
# right turn.

forward = [[-1,  0], # go up
           [ 0, -1], # go left
           [ 1,  0], # go down
           [ 0,  1]] # go right
forward_name = ['up', 'left', 'down', 'right']

# action has 3 values: right turn, no turn, left turn
action = [-1, 0, 1]
action_name = ['R', '#', 'L']

# EXAMPLE INPUTS:
# grid format:
#     0 = navigable space
#     1 = unnavigable space 
grid = [[1, 1, 1, 0, 0, 0],
        [1, 1, 1, 0, 1, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 1, 1, 0, 1, 1],
        [1, 1, 1, 0, 1, 1]]

init = [4, 3, 0] # given in the form [row,col,direction]
                 # direction = 0: up
                 #             1: left
                 #             2: down
                 #             3: right
                
goal = [2, 0] # given in the form [row,col]

cost = [2, 1, 20] # cost has 3 values, corresponding to making 
                  # a right turn, no turn, and a left turn

# EXAMPLE OUTPUT:
# calling optimum_policy2D with the given parameters should return 
# [[' ', ' ', ' ', 'R', '#', 'R'],
#  [' ', ' ', ' ', '#', ' ', '#'],
#  ['*', '#', '#', '#', '#', 'R'],
#  [' ', ' ', ' ', '#', ' ', ' '],
#  [' ', ' ', ' ', '#', ' ', ' ']]
# ----------

# ----------------------------------------
# modify code below
# ----------------------------------------

def optimum_policy2D(grid,init,goal,cost):
    N = len(grid)
    M = len(grid[0])
    value = [[99 for col in range(len(grid[0]))] for row in range(len(grid))]
    visit = [[0 for col in range(len(grid[0]))] for row in range(len(grid))]
    policy = [['≈' for col in range(len(grid[0]))] for row in range(len(grid))]
    
    que = deque([[goal[0], goal[1], 0, '*']])
    
    while len(que) > 0:
        r, c, v, _ = que.popleft()
        visit[r][c] = 1
        value[r][c] = v
        for act, act_name, cst in zip(action, action_name, cost):
            nr = r + forward[act][0]
            nc = c + forward[act][1]
            if (0 <= nr < N) and (0 <= nc < M) and visit[nr][nc] == 0 and grid[nr][nc] == 0:
                que.append([nr, nc, v+cst, act_name])
       
    visit = [[0 for col in range(len(grid[0]))] for row in range(len(grid))]
    for r in range(N):
        for c in range(M):
            if grid[r][c] == 1:
                continue
            ways = []
            for act, act_name, _ in zip(action, action_name, cost):
                nr = r + forward[act][0]
                nc = c + forward[act][1]
                if (0 <= nr < N) and (0 <= nc < M) and visit[nr][nc] == 0 and grid[nr][nc] == 0:
                    ways.append([value[nr][nc], act_name])
            if(len(ways) > 0):
                ways.sort()
                policy[r][c] = ways[0][1]
    policy[goal[0]][goal[1]] = '*'
    pprint(value)
    return policy

In [12]:
pprint(optimum_policy2D(grid,init,goal,cost))

[[99, 99, 99, 8, 10, 12],
 [99, 99, 99, 7, 99, 11],
 [0, 2, 4, 6, 8, 10],
 [99, 99, 99, 99, 99, 99],
 [99, 99, 99, 99, 99, 99]]
[['≈', '≈', '≈', 'R', 'L', 'L'],
 ['≈', '≈', '≈', '#', '≈', '#'],
 ['*', 'L', 'L', 'L', 'L', 'L'],
 ['≈', '≈', '≈', '#', '≈', '≈'],
 ['≈', '≈', '≈', '#', '≈', '≈']]
